import { Quote } from "./types/quotes";

export const quotes: Quote[] = [
  {
    quote: "Be yourself; everyone else is already taken.",
    author: "Oscar Wilde",
    _id: undefined,
    createdBy: "",
    adminApproved: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    quote: "The secret of getting ahead is getting started.",
    author: "Mark Twain",
    _id: undefined,
    createdBy: "",
    adminApproved: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    quote: "In the middle of difficulty lies opportunity.",
    author: "Albert Einstein",
    _id: undefined,
    createdBy: "",
    adminApproved: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    quote: "What you do today can improve all your tomorrows.",
    author: "Ralph Marston",
    _id: undefined,
    createdBy: "",
    adminApproved: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    quote: "It always seems impossible until it’s done.",
    author: "Nelson Mandela",
    _id: undefined,
    createdBy: "",
    adminApproved: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    quote: "If you can dream it, you can do it.",
    author: "Walt Disney",
    _id: undefined,
    createdBy: "",
    adminApproved: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    quote: "Stay hungry. Stay foolish.",
    author: "Steve Jobs",
    _id: undefined,
    createdBy: "",
    adminApproved: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    quote: "Whatever you are, be a good one.",
    author: "Abraham Lincoln",
    _id: undefined,
    createdBy: "",
    adminApproved: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    quote: "Strive not to be a success, but rather to be of value.",
    author: "Albert Einstein",
    _id: undefined,
    createdBy: "",
    adminApproved: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    quote: "Simplicity is the ultimate sophistication.",
    author: "Leonardo da Vinci",
    _id: undefined,
    createdBy: "",
    adminApproved: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    quote: "Life is short. Live it.",
    author: "Unknown",
    _id: undefined,
    createdBy: "",
    adminApproved: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    quote: "Act as if what you do makes a difference. It does.",
    author: "William James",
    _id: undefined,
    createdBy: "",
    adminApproved: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    quote: "Turn your wounds into wisdom.",
    author: "Oprah Winfrey",
    _id: undefined,
    createdBy: "",
    adminApproved: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    quote: "You miss 100% of the shots you don’t take.",
    author: "Wayne Gretzky",
    _id: undefined,
    createdBy: "",
    adminApproved: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    quote: "Dream big and dare to fail.",
    author: "Norman Vaughan",
    _id: undefined,
    createdBy: "",
    adminApproved: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    quote: "Don’t wait. The time will never be just right.",
    author: "Napoleon Hill",
    _id: undefined,
    createdBy: "",
    adminApproved: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    quote: "Well done is better than well said.",
    author: "Benjamin Franklin",
    _id: undefined,
    createdBy: "",
    adminApproved: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    quote: "Be the change that you wish to see in the world.",
    author: "Often attributed to Gandhi",
    _id: undefined,
    createdBy: "",
    adminApproved: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    quote: "Happiness is not by chance, but by choice.",
    author: "Jim Rohn",
    _id: undefined,
    createdBy: "",
    adminApproved: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    quote: "Action is the foundational key to all success.",
    author: "Pablo Picasso",
    _id: undefined,
    createdBy: "",
    adminApproved: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    quote: "Do something today that your future self will thank you for.",
    author: "Sean Patrick Flanery",
    _id: undefined,
    createdBy: "",
    adminApproved: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    quote:
      "It’s not the years in your life that count. It’s the life in your years.",
    author: "Abraham Lincoln",
    _id: undefined,
    createdBy: "",
    adminApproved: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    quote: "Either you run the day or the day runs you.",
    author: "Jim Rohn",
    _id: undefined,
    createdBy: "",
    adminApproved: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    quote: "Believe you can and you’re halfway there.",
    author: "Theodore Roosevelt",
    _id: undefined,
    createdBy: "",
    adminApproved: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    quote: "Failure is success if we learn from it.",
    author: "Malcolm Forbes",
    _id: undefined,
    createdBy: "",
    adminApproved: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    quote: "Life is 10% what happens to us and 90% how we react to it.",
    author: "Charles R. Swindoll",
    _id: undefined,
    createdBy: "",
    adminApproved: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    quote: "Start where you are. Use what you have. Do what you can.",
    author: "Arthur Ashe",
    _id: undefined,
    createdBy: "",
    adminApproved: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    quote: "What we think, we become.",
    author: "Buddha",
    _id: undefined,
    createdBy: "",
    adminApproved: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    quote:
      "Keep going. Everything you need will come to you at the perfect time.",
    author: "Unknown",
    _id: undefined,
    createdBy: "",
    adminApproved: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    quote: "Success is not final; failure is not fatal.",
    author: "Winston Churchill",
    _id: undefined,
    createdBy: "",
    adminApproved: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    quote: "A person who never made a mistake never tried anything new.",
    author: "Albert Einstein",
    _id: undefined,
    createdBy: "",
    adminApproved: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    quote: "Don’t let yesterday take up too much of today.",
    author: "Will Rogers",
    _id: undefined,
    createdBy: "",
    adminApproved: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    quote: "Everything you’ve ever wanted is on the other side of fear.",
    author: "George Addair",
    _id: undefined,
    createdBy: "",
    adminApproved: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    quote: "I have not failed. I’ve just found 10,000 ways that won’t work.",
    author: "Thomas Edison",
    _id: undefined,
    createdBy: "",
    adminApproved: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    quote: "If you want to lift yourself up, lift up someone else.",
    author: "Booker T. Washington",
    _id: undefined,
    createdBy: "",
    adminApproved: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    quote: "Don’t be pushed around by the fears in your mind.",
    author: "Roy T. Bennett",
    _id: undefined,
    createdBy: "",
    adminApproved: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    quote: "Small deeds done are better than great deeds planned.",
    author: "Peter Marshall",
    _id: undefined,
    createdBy: "",
    adminApproved: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    quote: "We may encounter many defeats but we must not be defeated.",
    author: "Maya Angelou",
    _id: undefined,
    createdBy: "",
    adminApproved: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    quote: "Be kind whenever possible. It is always possible.",
    author: "Dalai Lama",
    _id: undefined,
    createdBy: "",
    adminApproved: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    quote: "To succeed in life, you need two things: ignorance and confidence.",
    author: "Mark Twain",
    _id: undefined,
    createdBy: "",
    adminApproved: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    quote:
      "The only limit to our realization of tomorrow will be our doubts of today.",
    author: "Franklin D. Roosevelt",
    _id: undefined,
    createdBy: "",
    adminApproved: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    quote:
      "You can, you should, and if you’re brave enough to start, you will.",
    author: "Stephen King",
    _id: undefined,
    createdBy: "",
    adminApproved: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    quote: "If at first you don’t succeed, try, try again.",
    author: "Thomas H. Palmer",
    _id: undefined,
    createdBy: "",
    adminApproved: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    quote: "It’s kind of fun to do the impossible.",
    author: "Walt Disney",
    _id: undefined,
    createdBy: "",
    adminApproved: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    quote: "If opportunity doesn’t knock, build a door.",
    author: "Milton Berle",
    _id: undefined,
    createdBy: "",
    adminApproved: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    quote: "Fall seven times, stand up eight.",
    author: "Japanese Proverb",
    _id: undefined,
    createdBy: "",
    adminApproved: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    quote: "A journey of a thousand miles begins with a single step.",
    author: "Lao Tzu",
    _id: undefined,
    createdBy: "",
    adminApproved: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    quote: "Never regret anything that made you smile.",
    author: "Mark Twain",
    _id: undefined,
    createdBy: "",
    adminApproved: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    quote: "Die with memories, not dreams.",
    author: "Unknown",
    _id: undefined,
    createdBy: "",
    adminApproved: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    quote: "I can and I will. Watch me.",
    author: "Carrie Green (often credited)",
    _id: undefined,
    createdBy: "",
    adminApproved: false,
    createdAt: "",
    updatedAt: "",
  },
];
